set(CMAKE_SYSTEM_NAME       Generic)
set(CMAKE_SYSTEM_PROCESSOR  aarch64)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_AR                aarch64-none-elf-ar${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_ASM_COMPILER      aarch64-none-elf-as${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_C_COMPILER        aarch64-none-elf-gcc${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_CXX_COMPILER      aarch64-none-elf-g++${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_LINKER            aarch64-none-elf-ld${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_OBJCOPY           aarch64-none-elf-objcopy${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_RANLIB            aarch64-none-elf-ranlib${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_SIZE              aarch64-none-elf-size${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_STRIP             aarch64-none-elf-strip${CMAKE_EXECUTABLE_SUFFIX})

set(CMAKE_C_FLAGS           "-ffreestanding")
set(CMAKE_CXX_FLAGS         "${CMAKE_C_FLAGS}")

set(CMAKE_ASM_FLAGS_DEBUG   "-g" CACHE INTERNAL "")
set(CMAKE_ASM_FLAGS_RELEASE "" CACHE INTERNAL "")
set(CMAKE_C_FLAGS_DEBUG     "-Wall -Wextra -Os -g" CACHE INTERNAL "")
set(CMAKE_C_FLAGS_RELEASE   "-Os -DNDEBUG" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG}" CACHE INTERNAL "")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}" CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
